### ISSUE TITLE
Mobile Responsiveness 

### ISSUE THREAD

**Issue by theabhayprajapati** [fayazara/onelink#1]
Can I work on mobile responsiveness.

currently its like this.

![Screenshot_20230130_091442_Chrome.jpg](https://user-images.githubusercontent.com/88815641/215383253-be550a6c-cba1-40e7-8106-aa50250d429a.jpg)

**Comment by CHEWX** [comment]
PRrrrrrrrr

**Comment by fayazara** [comment]
@theabhayprajapati Sure, please go head and try to create a PR.

Let me know if you need any help here
